[package]

name = "scene"
version = "0.1.0"
authors = [
    "Dzmitry Malyshau <kvarkus@gmail.com>",
]

[lib]
name = "scene"
path = "src/lib.rs"

[dependencies.ecs]
path = "src/ecs/"

[dependencies.gltf]
path = "src/gltf/"

[dependencies.render]
path = "src/render/"
