[package]

name = "render"
version = "0.1.0"
authors = [
]

[lib]
name = "render"
path = "lib.rs"


[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"

[dependencies.ecs]
path = "../ecs"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"
